gamedat_objects = {
     1: { "objname": "pair of hands"},
     2: { "objname": "zorkmid"},
     3: { "objname": "way"},
     4: { "objname": "cretin"},
     5: { "objname": "you"},
     6: { "objname": "blast of air"},
     7: { "objname": "lurking grue"},
     8: { "objname": "ground"},
     9: { "objname": "sailor"},
    10: { "objname": "blessings"},
    11: { "objname": "such thing"},
    12: { "objname": "random object"},
    13: { "objname": "pseudo"},
    14: { "objname": "number"},
    15: { "objname": "Slide Room"},
    16: { "objname": "Coal Mine"},
    17: { "objname": "Coal Mine"},
    18: { "objname": "Coal Mine"},
    19: { "objname": "Coal Mine"},
    20: { "objname": "Ladder Bottom"},
    21: { "objname": "Ladder Top"},
    22: { "objname": "Smelly Room"},
    23: { "objname": "Squeaky Room"},
    24: { "objname": "Mine Entrance"},
    25: { "objname": "Canyon View"},
    26: { "objname": "Rocky Ledge"},
    27: { "objname": "Canyon Bottom"},
    28: { "objname": "On the Rainbow"},
    29: { "objname": "Aragain Falls"},
    30: { "objname": "Shore"},
    31: { "objname": "Frigid River"},
    32: { "objname": "White Cliffs Beach"},
    33: { "objname": "White Cliffs Beach"},
    34: { "objname": "Frigid River"},
    35: { "objname": "Frigid River"},
    36: { "objname": "Frigid River"},
    37: { "objname": "Chasm"},
    38: { "objname": "North-South Passage"},
    39: { "objname": "Damp Cave"},
    40: { "objname": "Deep Canyon"},
    41: { "objname": "East-West Passage"},
    42: { "objname": "Twisting Passage"},
    43: { "objname": "Winding Passage"},
    44: { "objname": "Narrow Passage"},
    45: { "objname": "Cold Passage"},
    46: { "objname": "Cave"},
    47: { "objname": "Cave"},
    48: { "objname": "Stream"},
    49: { "objname": "Stream View"},
    50: { "objname": "Reservoir South"},
    51: { "objname": "Strange Passage"},
    52: { "objname": "Maze"},
    53: { "objname": "Maze"},
    54: { "objname": "Maze"},
    55: { "objname": "Dead End"},
    56: { "objname": "Maze"},
    57: { "objname": "Grating Room"},
    58: { "objname": "Maze"},
    59: { "objname": "Maze"},
    60: { "objname": "Maze"},
    61: { "objname": "Dead End"},
    62: { "objname": "Maze"},
    63: { "objname": "Maze"},
    64: { "objname": "Maze"},
    65: { "objname": "Dead End"},
    66: { "objname": "Dead End"},
    67: { "objname": "Maze"},
    68: { "objname": "Maze"},
    69: { "objname": "Maze"},
    70: { "objname": "Maze"},
    71: { "objname": "East of Chasm"},
    72: { "objname": "Cellar"},
    73: { "objname": "stairs"},
    74: { "objname": "Clearing"},
    75: { "objname": "Forest Path"},
    76: { "objname": "Forest"},
    77: { "objname": "Forest"},
    78: { "objname": "Forest"},
    79: { "objname": "Behind House"},
    80: { "objname": "South of House"},
    81: { "objname": "North of House"},
    82: { "objname": ""},
    83: { "objname": "broken clockwork canary"},
    84: { "objname": "golden clockwork canary"},
    85: { "objname": "beautiful brass bauble"},
    86: { "objname": "broken jewel-encrusted egg"},
    87: { "objname": "jewel-encrusted egg"},
    88: { "objname": "Up a Tree"},
    89: { "objname": "bird's nest"},
    90: { "objname": "control panel"},
    91: { "objname": "wrench"},
    92: { "objname": "white cliffs"},
    93: { "objname": "cliff"},
    94: { "objname": "Studio"},
    95: { "objname": "ZORK owner's manual"},
    96: { "objname": "Engravings Cave"},
    97: { "objname": "wall with engravings"},
    98: { "objname": "viscous material"},
    99: { "objname": "tube"},
    100: { "objname": "Reservoir"},
    101: { "objname": "trunk of jewels"},
    102: { "objname": "The Troll Room"},
    103: { "objname": "tour guidebook"},
    104: { "objname": "torch"},
    105: { "objname": "Torch Room"},
    106: { "objname": "pedestal"},
    107: { "objname": "Round Room"},
    108: { "objname": "tan label"},
    109: { "objname": "ancient map"},
    110: { "objname": "sword"},
    111: { "objname": "wooden door"},
    112: { "objname": "switch"},
    113: { "objname": "stiletto"},
    114: { "objname": "thief"},
    115: { "objname": "large bag"},
    116: { "objname": "beautiful jeweled scarab"},
    117: { "objname": "wooden ladder"},
    118: { "objname": "Dead End"},
    119: { "objname": "small pile of coal"},
    120: { "objname": "Sandy Beach"},
    121: { "objname": "shovel"},
    122: { "objname": "skeleton key"},
    123: { "objname": "screwdriver"},
    124: { "objname": "Gas Room"},
    125: { "objname": "sapphire-encrusted bracelet"},
    126: { "objname": "Sandy Cave"},
    127: { "objname": "sand"},
    128: { "objname": "rusty knife"},
    129: { "objname": "rope"},
    130: { "objname": "Frigid River"},
    131: { "objname": "river"},
    132: { "objname": "rainbow"},
    133: { "objname": "Dome Room"},
    134: { "objname": "wooden railing"},
    135: { "objname": "prayer"},
    136: { "objname": "End of Rainbow"},
    137: { "objname": "pot of gold"},
    138: { "objname": "Loud Room"},
    139: { "objname": "platinum bar"},
    140: { "objname": "Dam Base"},
    141: { "objname": "pile of plastic"},
    142: { "objname": "punctured boat"},
    143: { "objname": "Clearing"},
    144: { "objname": "pile of leaves"},
    145: { "objname": "pile of bodies"},
    146: { "objname": "small piece of vitreous slag"},
    147: { "objname": "pair of candles"},
    148: { "objname": "Gallery"},
    149: { "objname": "painting"},
    150: { "objname": "Mirror Room"},
    151: { "objname": "mirror"},
    152: { "objname": "Mirror Room"},
    153: { "objname": "mirror"},
    154: { "objname": "Dam Lobby"},
    155: { "objname": "matchbook"},
    156: { "objname": "magic boat"},
    157: { "objname": "Machine Room"},
    158: { "objname": "machine"},
    159: { "objname": "leak"},
    160: { "objname": "small mailbox"},
    161: { "objname": "leaflet"},
    162: { "objname": "red buoy"},
    163: { "objname": "large emerald"},
    164: { "objname": "brass lantern"},
    165: { "objname": "leather bag of coins"},
    166: { "objname": "burned-out lantern"},
    167: { "objname": "Maze"},
    168: { "objname": "skeleton"},
    169: { "objname": "nasty knife"},
    170: { "objname": "jade figurine"},
    171: { "objname": "huge diamond"},
    172: { "objname": "Reservoir North"},
    173: { "objname": "hand-held air pump"},
    174: { "objname": "grating"},
    175: { "objname": "Egyptian Room"},
    176: { "objname": "crack"},
    177: { "objname": "stone barrow"},
    178: { "objname": "Stone Barrow"},
    179: { "objname": "stone door"},
    180: { "objname": "West of House"},
    181: { "objname": "door"},
    182: { "objname": "boarded window"},
    183: { "objname": "trap door"},
    184: { "objname": "dam"},
    185: { "objname": "Cyclops Room"},
    186: { "objname": "cyclops"},
    187: { "objname": "Atlantis Room"},
    188: { "objname": "crystal trident"},
    189: { "objname": "clove of garlic"},
    190: { "objname": "Treasure Room"},
    191: { "objname": "chalice"},
    192: { "objname": "carpet"},
    193: { "objname": "Living Room"},
    194: { "objname": "trophy case"},
    195: { "objname": "blue button"},
    196: { "objname": "red button"},
    197: { "objname": "brown button"},
    198: { "objname": "yellow button"},
    199: { "objname": "Maintenance Room"},
    200: { "objname": "group of tool chests"},
    201: { "objname": "Attic"},
    202: { "objname": "table"},
    203: { "objname": "Kitchen"},
    204: { "objname": "kitchen table"},
    205: { "objname": "chute"},
    206: { "objname": "Timber Room"},
    207: { "objname": "broken timber"},
    208: { "objname": "gold coffin"},
    209: { "objname": "sceptre"},
    210: { "objname": "broken lantern"},
    211: { "objname": "black book"},
    212: { "objname": "Altar"},
    213: { "objname": "altar"},
    214: { "objname": "green bubble"},
    215: { "objname": "Dam"},
    216: { "objname": "bolt"},
    217: { "objname": "troll"},
    218: { "objname": "bloody axe"},
    219: { "objname": "red hot brass bell"},
    220: { "objname": "Temple"},
    221: { "objname": "brass bell"},
    222: { "objname": "Bat Room"},
    223: { "objname": "bat"},
    224: { "objname": "brown sack"},
    225: { "objname": "lunch"},
    226: { "objname": "Shaft Room"},
    227: { "objname": "basket"},
    228: { "objname": "Drafty Room"},
    229: { "objname": "basket"},
    230: { "objname": "Land of the Dead"},
    231: { "objname": "crystal skull"},
    232: { "objname": "Entrance to Hades"},
    233: { "objname": "number of ghosts"},
    234: { "objname": "chimney"},
    235: { "objname": "kitchen window"},
    236: { "objname": "glass bottle"},
    237: { "objname": "quantity of water"},
    238: { "objname": "water"},
    239: { "objname": "Forest"},
    240: { "objname": "mountain range"},
    241: { "objname": "tree"},
    242: { "objname": "forest"},
    243: { "objname": "white house"},
    244: { "objname": "songbird"},
    245: { "objname": "granite wall"},
    246: { "objname": "surrounding wall"},
    247: { "objname": ""},
    248: { "objname": "set of teeth"},
    249: { "objname": ""},
    250: { "objname": "board"},
};

